---
name: Feature
description: Submit a Feature for Design which Has Been Submitted as an Idea and has been voted on
labels:
  - type/feature
  - status/needs-design
  - priority/normal
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature issue. Please review the following requirements before
        submitting this issue type:

        	1. Ensure an [Idea](https://github.com/authelia/authelia/discussions/new?category=ideas) has been created
        	   and voted on sufficiently before creating this issue type.
  - type: dropdown
    id: milestone
    attributes:
      label: Suggested Milestone
      description: What milestone is suggested for this feature?
      options:
        - v4.36.0
        - v4.37.0
        - v4.38.0
        - v4.39.0
        - v5.0.0
    validations:
      required: true
  - type: input
    id: idea-discussion
    attributes:
      label: Discussion Idea Number
      description: 'The Discussion Number prefixed with # which this feature is linked to'
      placeholder: '#xxxx'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the feature in detail
    validations:
      required: false
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Provide any relevant specification or other documentation if applicable
    validations:
      required: false
...
